version: '3.8'

networks:
  netw:
    driver: bridge

services:
  mongodatabase:
    image: mongo:latest
    container_name: mongodatabase
    volumes:
      - ./data:/dumbdata
    restart: on-failure:3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
      - MONGO_INITDB_DATABASE=metabase
    ports:
      - "27017:27017"
    networks:
    - netw

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: on-failure:3
    ports:
      - "3000:3000"
    environment:
      - MB_DB_DBNAME=metabase
      - MB_DB_USER=lappis
      - MB_DB_PASS=lappis
      - MB_DB_FILE=/app/metabase-data/metabase.db
    volumes:
      - ./metabase:/app/metabase-data
    networks:
      - netw
    depends_on:
      - mongodatabase
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lappis
      - POSTGRES_PASSWORD=lappis
      - POSTGRES_DB=metabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: app
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/src
    command: python main.py
    volumes:
      - ./:/app
    depends_on:
      - mongodatabase
    ports:
      - "5000:5000"
    networks:
      - netw

volumes:
  pgdata:
